name: Validación

on:
  pull_request:

permissions:
  contents: read

jobs:
  estandares-php:
    name: Composer, PHP, WPCS y PHPUnit
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Configurar PHP y Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          tools: composer:v2
          coverage: none

      - name: Instalar dependencias
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Validar
        run: composer check
